language: cpp

matrix:
    include:
        - os: linux
          dist: trusty
          compiler: gcc
          addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
              packages:
                - g++-7
          env:
            - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"


before_install:
    - eval "${MATRIX_EVAL}"

script:
    - mkdir build
    - cd build/
    - cmake ../ -DUNIT_TEST=On
    - cmake --build .
    - ctest
